# The MIT License (MIT)
#
# Copyright (C) 2025 Fabrício Barros Cabral
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included
# in all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.
---
name: latex-release
env:
  DOCUMENT: document
'on':
  push:
    tags:
      - '*'
jobs:
  latex-release:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Compile LaTeX
        uses: xu-cheng/latex-action@v3
        with:
          root_file: ${{ env.DOCUMENT }}.tex
          # yamllint disable-line rule:line-length
          post_compile: "mv ${{ env.DOCUMENT }}.pdf ${{ env.DOCUMENT }}-${{ github.ref_name }}.pdf"
      - name: Upload PDF
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.DOCUMENT }}-${{ github.ref_name }}
          path: ${{ env.DOCUMENT }}-${{ github.ref_name }}.pdf
      - name: Release PDF
        uses: softprops/action-gh-release@v2
        with:
          files: ${{ env.DOCUMENT }}-${{ github.ref_name }}.pdf
          generate_release_notes: true
