# SPDX-FileCopyrightText: Copyright (c) 2025 Fabrício Barros Cabral
# SPDX-License-Identifier: MIT
---
name: latex-lint
'on':
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  latex-lint:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Lint LaTeX files
        uses: xu-cheng/texlive-action@v2
        with:
          scheme: full
          run: lacheck *.tex
