# The MIT License (MIT)
#
# Copyright (C) 2025 Fabrício Barros Cabral
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included
# in all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

version = 1
[[annotations]]
path = [
    ".DS_Store",
    ".gitattributes",
    ".gitignore",
    ".pdd",
    ".gitmodules",
    ".latexmkrc",
    ".texqc",
    ".texsc",
    "**.jpg",
    "**.json",
    "**.md",
    "**.pdf",
    "**.png",
    "**.svg",
    "**.txt",
    "**.vm",
    "**/.DS_Store",
    "**/.gitignore",
    "**/.pdd",
    "**/.gitmodules",
    "**/.latexmkrc",
    "**/.texqc",
    "**/.texsc",
    "**/*.csv",
    "**/*.jpg",
    "**/*.json",
    "**/*.md",
    "**/*.pdf",
    "**/*.png",
    "**/*.svg",
    "**/*.txt",
    "**/*.vm",
    "**/*.puml",
    "**/aspell.en.pws",
    "**/DEPENDS.txt",
    "aspell.en.pws",
    "**/CNAME",
    "DEPENDS.txt",
    "CNAME",
    "README.md",
    "renovate.json",
    "rc",
]
precedence = "override"
SPDX-FileCopyrightText = "Copyright (c) 2025 Fabrício Barros Cabral"
SPDX-License-Identifier = "MIT"
